import Link from 'next/link'
import './globals.css'
import { Control } from './Control';

export const metadata = {
  title: 'WEB tutorial',
  description: 'Generated by egoing',
}

export default async function RootLayout({ children }) {
  // db.json 데이터를 읽어오기 위한 과정
  /*
    ※ 캐시 설정
    1. next : revalidate: 10 => 10초동안만 캐시 유지
    2. cache: 'no-store' => 캐시를 저장하지 않는다
   */
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URI+'topics', { cache: 'no-cache'}); // 요청
  const topics = await resp.json(); // 결과 받기
  
  
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>        
        {/* <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol> */}
        <ol>
        {
          topics.map(topic => {
            return <li><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })
        }
        </ol>
        { children }
        {/*server component 안에서 client component를 분리하기 위한 절차 */}
        <Control />
      </body>
    </html>
  )
}
